version: '3'
services:
#  nodejs-server:
#    build:
#      context: ./api
#    ports:
#      - "3080:3080"
#    container_name: node-api
#    volumes:
#      - ./api:/usr/src/app/api
#      - /usr/src/app/api/node_modules
  kunst_diplom_doku_js:
    image: kunst_diplom_doku_js
    build:
      context: ./
      dockerfile: ./docker/react/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend
    container_name: kunst_diplom_doku_js
    volumes:
      - ./src:/usr/src/app/my-app/src
      - ./public:/usr/src/app/my-app/public
#      - /usr/src/app/my-app/node_modules
    environment:
      - VIRTUAL_HOST=diplom.doku.mavinbe.xyz

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  proxy_server:
    image: proxy_server
    build:
      context: ./docker/nginx
    ports:
      - "3001:80"
    networks:
      - frontend
    container_name: proxy_server

networks:
  frontend: