export const works_config = [
  {
    slug: "ot_noise",
    name: "o.T.(noise)",
    thumbnail: "2016_03_30_IMG_2353_print_v2.gif",
    type: "img",
    src: "2016_03_30_IMG_2353_print_v2_smaller.jpg",
    //api_video_code: "vi54sj9dAakOHJXKrUycCQZp"
    year: 2016,
    background_color: "#d9dbc2",
    width: 1980,
    height: 594,
    comment:"bilddatei",
    material: "fine art print",
    dimensions: "100cm x 30cm",
  },
  {
    slug: "radmaschine_spielen",
    name: "radmaschine&nbsp;version \"spielen\"",
    thumbnail: "1 2 Screen A.gif",
    type: "video",
    api_video_code: "vi6AdoUjNTkEfpxoFd9RxJbc",
    year: 2016,
    background_color: "#5701a7",
    width: 640,
    height: 272,
    comment:"videodatei",
    material: "2-kanal-performance-video",
    dimensions: "2:16min",
  },
  {
    slug: "radmaschine_gips",
    name: "radmaschine&nbsp;version \"gips\"",
    thumbnail: "GOPR3912.gif",
    type: "video",
    api_video_code: "vi5j0SnnM2ak4HOaYzY2UZZ6",
    year: 2017,
    background_color: "#B23850",
    width: 1280,
    height: 720,
    comment:"atelieraufbau",
    material: "installation, motor, stahl, gips",
    dimensions: "70cm x 200cm x 50cm",
    volume: 0.1,
  },
  {
    slug: "radmaschine_version_dark_horses",
    name: "radmaschine&nbsp;version \"dark&nbsp;horses\"",
    thumbnail: "IMG_3131.gif",
    type: "video",
    api_video_code: "vi3dJDzb8Nl87vZ5rZPaAj8d",
    year: 2017,
    background_color: "#ffb800",
    width: 1920,
    height: 1080,
    comment:"ausstellungsaufbau",
    material: "installation, motor, stahl, gips, fahrradreifen",
    dimensions: "70cm x 200cm x 50cm",
    volume: 1.0,
  },
  {
    slug: "post_hopo_1",
    name: "post-hopo 1",
    thumbnail: "Starren Dummy.gif",
    type: "video",
    api_video_code: "vi240tdYJZbAbbFe7YJ2Uy76",
    year: 2018,
    background_color: "#00da6c",
    width: 1920,
    height: 1080,
    comment:"1min videodatei ausschnitt",
    material: "video projektion",
    dimensions: "18min loop",
  },
  {
    slug: "gleich_gehts_weiter_post_hopo_2",
    name: "gleich gehts weiter - post-hopo 2",
    thumbnail: "Follow_G_small.gif",
    type: "video",
    api_video_code: "vi6XUXvwPwsiinPaCMnxquy7",
    year: 2018,
    background_color: "#000dff",
    width: 640,
    height: 336,
    comment:"videodatei ",
    material: "video",
    dimensions: "1:22min",
  },
  {
    slug: "look_what_i_ve_found",
    name: "look what i've found",
    thumbnail: "look what i\\'ve found.gif",
    type: "video",
    api_video_code: "vi5o2r7BlY7fXM9aTZRJQ34z",
    year: 2019,
    background_color: "#b00000",
    width: 1728,
    height: 1080,
    comment:"screen capture",
    material: "glasstisch, stuhl, notebook, video",
    dimensions: "20:30min",
  },
  {
    slug: "no_show",
    name: "no show",
    thumbnail: "abc2_cuted_no_works.gif",
    type: "video",
    api_video_code: "vi5G1Z3iIWID0oZrM0bXZDsy",
    year: 2019,
    background_color: "#45b561",
    width: 1920,
    height: 1080,
    comment: "screen capture",
    material: "live-video-installation",
    dimensions: "endlos",
  },
  {
    slug: "trek",
    name: "trek",
    thumbnail: "2020-01-31T17-40-25-000_live.gif",
    type: "video",
    api_video_code: "vi5frhdx5mBensTwju0Yfv0C",
    year: 2020,
    background_color: "#ff6200",
    width: 2880,
    height: 1620,
    comment: "screen capture",
    material: "live-video-installation",
    dimensions: "endlos - 10 min blöcke",
  },
  {
    slug: "four_rooms",
    name: "four rooms",
    thumbnail: "four_rooms_07.gif",
    type: "video",
    api_video_code: "viImqk4sUU8nN6Dl57mSZiX",
    year: 2021,
    background_color: "#ff0090",
    width: 1920,
    height: 1444,
    comment: "screen capture",
    material: "live-video-installation",
    dimensions: "endlos",
  }
]


/*
 {getCol('2016_03_30_IMG_2353_print_v2.gif')}
        {getCol('1 2 Screen A.gif')}
        {getCol('GOPR3912.gif')}
        {getCol('IMG_3131.gif')}
        {getCol('Starren Dummy.gif')}
        {getCol('Follow_G_small.gif')}
        {getCol('look what i\'ve found.gif')}
        {getCol('abc2_cuted_no_works.gif')}
        {getCol('2020-01-31T17-40-25-000_live.gif')}
        {getCol('video.gif')}
 */